### ISSUE TITLE
Parsing of property files is incomplete

### ISSUE THREAD

**Issue by komu** [io-german/java-properties-flat-loader#1]
Comments, alternative separators, line continuations and various are things are all missing. (See [Properties.load()](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.Reader-) for full specification of the property file format.)

It could be useful to use [java-properties](https://www.npmjs.com/package/java-properties) for parsing property files. Although it's also missing some of the things, it supports more of the format. (And I already filed multiple issues against that.)

**Comment by io-german** [comment]
Thanks for creating this issue. I'll look into it and will update the package in a day or two.

**Comment by komu** [comment]
Thanks!

I looked further and found [properties](https://www.npmjs.com/package/properties)-package, which seems to have a much more complete support for Java properties than [java-properties](https://www.npmjs.com/package/java-properties), so perhaps that's a better choice.

**Comment by komu** [comment]
I added a custom loader to my project for now. It ended up being simply this:

``` javascript
var properties = require("properties");

module.exports = function (content) {
    this.cacheable && this.cacheable();

    var callback = this.async();

    properties.parse(content, function (error, result) {
        if (error) return callback(error);
        callback(null, "module.exports = " + JSON.stringify(result) + ";");
    });
};
```

Feel free to use this if you want.

**Comment by io-german** [comment]
Since you interested in this fix I guess you should check the pull request #2 before it is merged.

I'll deploy the module right after the merge.

**Comment by io-german** [comment]
Module is updated on the NPM repo. Update it to version `1.0.0` in your `package.json`.
